# Generated by Django 3.1.7 on 2021-05-24 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('cee0ca06-9712-4dff-a0ca-c74ca7aa6149'), unique=True, unique_for_date=True),
        ),
    ]
