# Generated by Django 3.1.7 on 2021-05-28 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210524_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b800c13e-913b-43ec-95ab-2ce50ad81ae5'), unique=True, unique_for_date=True),
        ),
    ]
