# Generated by Django 3.1.7 on 2021-05-16 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210414_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='profile_img/doc.png', upload_to='profile_img', verbose_name='profile img'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('84e009ea-632c-4310-beb4-242ca2379c46'), unique=True, unique_for_date=True),
        ),
    ]
