# Generated by Django 3.1.7 on 2021-05-16 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210516_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('7e7a1b7f-49bb-4d0d-bc79-7b4872d50fa1'), unique=True, unique_for_date=True),
        ),
    ]
