# Generated by Django 3.1.7 on 2021-05-28 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210528_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9428b1f6-c6d5-40a8-aa2c-f8e1c5fe06cf'), unique=True, unique_for_date=True),
        ),
    ]
