# Generated by Django 3.1.7 on 2021-05-28 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210528_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a0d2d09e-d469-4755-b441-50f5b3541bcd'), unique=True, unique_for_date=True),
        ),
    ]
