# Generated by Django 3.1.7 on 2021-05-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='city', max_length=90)),
                ('latitude', models.CharField(default='00.000000000', max_length=40, unique=True)),
                ('longitude', models.CharField(default='00.000000000', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, unique=True)),
                ('iso3', models.CharField(default='c3', max_length=3, unique=True)),
                ('iso2', models.CharField(default='c2', max_length=2, unique=True)),
                ('phone_code', models.CharField(default='+000', max_length=4, unique=True)),
                ('capital', models.CharField(default='', max_length=60, unique=True)),
                ('latitude', models.CharField(default='00.000000000', max_length=40)),
                ('longitude', models.CharField(default='00.000000000', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Practice Logo')),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Active', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(default='Zone Name', max_length=30, unique=True)),
                ('gmt_offset', models.IntegerField(default=0)),
                ('gmt_offsetname', models.CharField(default='UTC=00:00', max_length=30, unique=True)),
                ('abbreviation', models.CharField(default='ABBR', max_length=4, unique=True)),
                ('tz_name', models.CharField(default='TimeZone Name', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='AAA', max_length=4)),
                ('name', models.CharField(default='province', max_length=90)),
                ('state_code', models.CharField(default='StCd', max_length=4, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(default='Reg Number', max_length=30)),
                ('reg_date', models.DateField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practice')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.UUIDField(auto_created=True, default=uuid.UUID('ece2e0eb-e24e-44c9-8ded-4a82723d88e9'), unique=True, unique_for_date=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(default='Reg Number', max_length=20, unique=True)),
                ('reg_status', models.BooleanField(default=False)),
                ('register', models.CharField(default='Register', max_length=127, unique=True)),
                ('reg_board', models.CharField(default='Board', max_length=127)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(default='', max_length=100)),
                ('date_obtained', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(default='Practice Type', max_length=50, unique=True)),
                ('field', models.CharField(default='Practice Field', max_length=60)),
                ('speciality', models.CharField(default='Practice Speciality', max_length=90)),
                ('sub_speciality', models.CharField(default='', max_length=90)),
                ('start_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('origin', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDoctor', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.practice')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
    ]
