# Generated by Django 3.1.7 on 2021-05-28 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='lid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d8e7bd7c-9d31-4806-bb32-32adf7c6706e'), unique=True, unique_for_date=True),
        ),
    ]
