# Generated by Django 3.1.7 on 2021-05-28 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210528_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default='+000', max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='lid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e94b0223-2a13-48f6-832f-feef819edc12'), unique=True, unique_for_date=True),
        ),
    ]
